/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import static org.junit.Assert.assertNotNull;
import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should not be null", classUnderTest);
        // You can add other assertions here if needed
    }
}
